# Generated by Django 4.1.7 on 2023-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='RecoveryMethode',
            new_name='MaintenanceCompany',
        ),
        migrations.AlterField(
            model_name='complainte',
            name='recoveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recoverymethod'),
        ),
    ]
