# Generated by Django 4.1.7 on 2023-03-01 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complainte_maintenancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 3, 1)),
        ),
    ]
