# Generated by Django 4.1.7 on 2023-03-02 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_complainte_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='factoryNumberEngene',
            new_name='factoryNumberEngine',
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 3, 2)),
        ),
    ]
