# Generated by Django 4.1.7 on 2023-03-02 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_machine_modelmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientcompany', verbose_name='Client Company'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='deliveryAddress',
            field=models.CharField(max_length=256, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='driveAxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driveaxel', verbose_name='Drive Axel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engine', verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.CharField(default='стандартная комплектация', max_length=256, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberDriveAxel',
            field=models.CharField(max_length=64, unique=True, verbose_name='Drive Axel Factory Number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberEngine',
            field=models.CharField(max_length=64, unique=True, verbose_name='Engine Factory Number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberMachine',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Machine factory number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberSteringAxel',
            field=models.CharField(max_length=64, unique=True, verbose_name='Stering Axel Factory Number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberTransmission',
            field=models.CharField(max_length=64, unique=True, verbose_name='Transmission Factory Number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='receiver',
            field=models.CharField(max_length=64, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicecompany', verbose_name='Service Company'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 3, 2), verbose_name='Shiping Date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steringAxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.steringaxel', verbose_name='Stering Axel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supplyContract',
            field=models.CharField(max_length=64, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transmission', verbose_name='Transmission'),
        ),
    ]
